# Generated by Django 4.2.11 on 2024-03-24 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
