# Generated by Django 4.2.11 on 2024-04-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comments_created_at_comments_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('LS', 'Lifestyle'), ('W', 'World'), ('BS', 'Business'), ('TC', 'Tech')], default='TC', max_length=2),
        ),
    ]
